### PR TITLE
Review for some grammar improvement

### PR DESCRIPTION
**Pull request by mpietro40**
I've done a review in order to improve the italian language and fix some minor grammar mistake.
I've added also a missing point in the line 150

### CODE REVIEW

**Comment by Jessica-Larsen** [comment]
@mpietro40 thank you for the contribution! 
@xdatap1 would you be able to review these changes and provide your feedback so we can get these improvements merged in?

**Comment by xdatap1** [comment]
Thank you @mpietro40 for your contribution, really appreciated! I will review the changes asap, hopefully in a few days. Cheers

**Comment by xdatap1** [comment]
I like the improvements. Unfortunately there are, in this pull request, few typos that needs to be fixed before merging:
- Line 68: autonimia (autonomia)
- Line 93: realizzandoo (realizzando)
- Line 253: deployment (Deployment). Referring to the framework component and not the general term, the name require the uppercase. We used the same for the other components.

Can you fix these and commit again so they came in the same pull request? Thanks in advance.

**Comment by mpietro40** [comment]
I've done the suggested typo fix
Line 68: autonimia (autonomia)
Line 93: realizzandoo (realizzando)
Line 253: deployment (Deployment).

**Comment by mpietro40** [comment]
Removed conflict and submitted the approved changes

**Pull request merged**
